# lists order and title of each collection
collections:
  # identifiers must be unique
  - start: 
    en-US: Getting started
    ja-JP: Bolt 入門ガイド 
  - reference:
    en-US: Reference
    ja-JP: リファレンス
  - basic: 
    en-US: Basic concepts
    ja-JP: 基本的な概念
  - steps: 
    en-US: Workflow steps
    ja-JP: ワークフローステップ
  - advanced: 
    en-US: Advanced concepts
    ja-JP: 応用コンセプト
  - deployments:
    en-US: Deployments
    # TODO: translate
    ja-JP: Deployments
  - tutorials:
    en-US: Tutorials
    # TODO: translate
    ja-JP: Tutorials
  - contribute: 
    en-US: Contributing
    ja-JP: 貢献

# lists entry slugs belonging to each collection
contents:
  start:
    - getting-started
  reference:
    - reference
  basic:
    - message-listening
    - message-sending
    - event-listening
    - web-api
    - action-listening
    - action-respond
    - acknowledge
    - shortcuts
    - commands
    - creating-modals
    - updating-pushing-views
    - view-submissions
    - publishing-views
    - options
    - authenticating-oauth
    - socket-mode
  steps:
    - creating-steps
    - adding-editing-steps
    - saving-steps
    - executing-steps
  advanced:
    - error-handling
    - authorization
    - token-rotation
    - conversation-store
    - global-middleware
    - listener-middleware
    - context
    - logging
    - receiver
    - custom-routes
  deployments: 
    - aws-lambda
    - heroku
  

