# This workflow will eventually handle publishing changes within /docs to Contentful CMS. 
# For more information, see our main DevTools docs migration project @
# https://paper.dropbox.com/doc/DevTools-docs-migration--BMeZ~P1MCa~mn~mlMIED371eAg-iSKF6HsbGzWnUJyZm3QPk

name: Publish to CMS

# workflow triggers
on:
  push:
    branches: [ sj_cms-workflow, main ]   # testing only
    paths:
    # trigger on changes matching paths:
    - 'docs/**'
  workflow_dispatch:

jobs:   
  publish:
    runs-on: macos-latest
    steps:
      - name: Checkout current project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: sets up nodejs runtime
        uses: actions/setup-node@v2
      - name: install deps
        run: npm install
      - name: setup git config
        run: |
          git config user.name "Content Management Bot"
          git config user.email "<>"
      # - name: get changed files (orig)
      #   id: getfile
      #   run: |
      #     echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs"   
      - name: get changed files 
        id: getfile
        run: |
          IFS=" "  
          read -ra filearr <<< "$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)"
          for i in "${filearr[@]}"
          do
          echo "$i"
          done 
          echo "::set-output name=files::${filearr}"
      - name: Runs the publish script
        env: 
          CONTENTFUL_API_KEY: ${{ secrets.CONTENTFUL_API_KEY }} 
          TOKEN: ${{ secrets.TOKEN }}
          SHA: ${{ github.sha }}
          ACTOR: ${{ github.actor }}
          REPOSITORY: ${{ github.repository }}
          EVENT: ${{ toJson(github.event) }}
          FILES_CHANGED: ${{ fromJson(toJson(steps.getfile.outputs.files)) }}
        run: npm run publish