# This workflow will eventually handle publishing changes within /docs to Contentful CMS. 
# For more information, see our main DevTools docs migration project @
# https://paper.dropbox.com/doc/DevTools-docs-migration--BMeZ~P1MCa~mn~mlMIED371eAg-iSKF6HsbGzWnUJyZm3QPk

name: Publish to CMS

# workflow triggers
on:
  push:
    branches: [ sj_cms-workflow, main ]   # testing only
    paths:
    # trigger on changes matching paths:
    - 'docs/**'
  workflow_dispatch:

jobs:   
  publish:
    runs-on: macos-latest
    steps:
      # testing only
      - name: Checkout current project
        uses: actions/checkout@v2
      - name: sets up nodejs runtime
        uses: actions/setup-node@v2
      - name: install deps
        run: npm install
      - name: Runs the publish script
        run: node src/publish.js
