# This workflow will eventually handle publishing changes within /docs to Contentful CMS. 
# For more information, see our main DevTools docs migration project @
# https://paper.dropbox.com/doc/DevTools-docs-migration--BMeZ~P1MCa~mn~mlMIED371eAg-iSKF6HsbGzWnUJyZm3QPk

name: Publish to CMS

# workflow triggers
on:
  workflow_dispatch:
    inputs: 
      name: 'Workflow dispatch'
  push:
    branches: [ cms-workflow, main ]   # testing only
    paths:
    # trigger on changes matching paths:
    - 'docs/**'

jobs:   
  publish:
    runs-on: macos-latest
    steps:
      - name: Checkout current project
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: sets up nodejs runtime
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: install deps
        run: npm install
      - name: setup git config
        run: |
          git config user.name "Content Management Bot"
          git config user.email "<>"
      - name: get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | xargs)"
      - name: get all files
        id: getall
        run: |
          echo "::set-output name=files::$(git ls-files 'docs/[^.]*' |xargs)"
      - name: Runs the publish script
        env: 
          CONTENTFUL_API_KEY: ${{ secrets.CONTENTFUL_API_KEY }} 
          TOKEN: ${{ secrets.TOKEN }}
          SHA: ${{ github.sha }}
          AUTHOR: ${{ github.actor }}
          REPOSITORY: ${{ github.repository }}
          EVENT: ${{ toJson(github.event) }}
          FILES_CHANGED: ${{ steps.getfile.outputs.files }}
          ALL_FILES: ${{ steps.getall.outputs.files }}
        run: npm run publish