# This workflow will eventually handle publishing changes within /docs to Contentful CMS. 
# For more information, see our main DevTools docs migration project @
# https://paper.dropbox.com/doc/DevTools-docs-migration--BMeZ~P1MCa~mn~mlMIED371eAg-iSKF6HsbGzWnUJyZm3QPk

name: Publish to CMS

# workflow triggers
on:
  push:
    branches: [ sj_cms-workflow, main ]   # testing only
    paths:
    # trigger on changes matching paths:
    - 'docs/**'
  workflow_dispatch:

jobs:   
  publish:
    runs-on: macos-latest
    steps:
      # testing only
      - name: Get env vars 
        run: echo {{ env.GITHUB_WORKFLOW \n env.GITHUB_ACTOR \n env.GITHUB_REPOSITORY \n env.GITHUB_SHA \n }}
      - name: Get changed files
        run: git diff-tree --no-commit-id --name-only -r {{ env.GITHUB_SHA }}
      - name: Checkout current project
        uses: actions/checkout@v2
      - name: sets up nodejs runtime
        uses: actions/setup-node@v2
      - name: install deps
        run: npm install
      - name: Runs the publish script
        env: 
          CONTENTFUL_API_KEY: ${{ secrets.CONTENTFUL_API_KEY }} 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run publish